// Least-privilege Atlas database roles (translate via Atlas UI/CLI:
// Database > Roles). Definitions here are the source of truth; the script
// prints `db.createRole`/`db.createUser` commands for the ops runbook.
//
// - sih26App        : readWrite on app collections, NO collection/schema
//                     management (cannot create collections or indexes), no
//                     access to schema_migrations.
// - sih26ReadOnly   : read-only across collections (dashboards, support).
// - sih26Migrator   : readWrite + dbAdmin (index/collection management) —
//                     used ONLY by the migration runner; access is audited.
// - sih26BreakGlass : interactive, individually-approved production writes;
//                     every use must append an audit_events record (break-glass
//                     runbook has its own audit trail).

export const ROLES = [
  {
    role: 'sih26App', privileges: [
      { resource: { db: 'sih26_dev', collection: '' }, actions: ['find', 'insert', 'update', 'remove'] },
      // NO: createCollection, createIndex, collMod, dropCollection
    ],
  },
  { role: 'sih26ReadOnly', privileges: [{ resource: { db: 'sih26_dev', collection: '' }, actions: ['find'] }] },
  { role: 'sih26Migrator', privileges: [{ resource: { db: 'sih26_dev', collection: '' }, actions: ['find', 'insert', 'update', 'remove', 'createCollection', 'createIndex', 'collMod', 'dropCollection', 'listCollections', 'listIndexes'] }] },
  { role: 'sih26BreakGlass', privileges: [{ resource: { db: 'sih26_dev', collection: '' }, actions: ['find', 'insert', 'update', 'remove'] }] },
];

export function printRoleScript(dbName = 'sih26_dev') {
  const lines = ['// Generated by roles/roles.js — run in a mongo shell with cluster admin rights.'];
  for (const r of ROLES) {
    lines.push(`db.createRole({ role: '${r.role}', privileges: ${JSON.stringify(r.privileges)}, roles: [] })`);
  }
  lines.push(`// Grant example: db.createUser({ user: 'sih26_app', pwd: '<secret>', roles: [{ role: 'sih26App', db: '${dbName}' }] })`);
  lines.push('// Least-privilege checks are verified by apps/api/test (DB-ACCEPT-005 / DB-BACKUP-009).');
  return lines.join('\n');
}

if (process.argv[1]?.endsWith('roles.js')) {
  console.log(printRoleScript());
}
